# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=120)),
                ('courseDescription', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
