# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 05:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20170310_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='couserlist',
            name='preview',
            field=models.CharField(default='www', max_length=200),
        ),
        migrations.AddField(
            model_name='couserlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
