# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-14 06:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170314_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couserlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
