# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170315_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couserlist',
            old_name='courseName',
            new_name='course_name',
        ),
    ]
