# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170316_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='couserlist',
            name='videoID',
            field=models.CharField(default='IT8s6gPsqUg', max_length=11),
        ),
    ]
