# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_couserlist_videoid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couserlist',
            old_name='videoID',
            new_name='videoId',
        ),
    ]
